### ISSUE TITLE
bug: texture issues

### ISSUE THREAD

**Issue by slabcache** [mxswat/pz-transmog-definitive-edition#13]
Say a zombie spawned with a hat, the hat on the zombie would be invisible. If the hat is knocked off a zombie, it will either drop as a question mark, or as a 2D sprite. If a player wears it, then everything is fine, model shows up and all.

**Comment by mxswat** [comment]
Read, the mod description. It's a known bug.

**Comment by mxswat** [comment]
![image](https://github.com/user-attachments/assets/c2f8b0af-9631-4138-9891-0d9d447f7a55)

**Comment by slabcache** [comment]
Came here to close the issue since I missed the first point and re-read it. Seems like you've done that for me, apologies.

**Comment by mxswat** [comment]
No worries, it happens.
