### ISSUE TITLE
Transmog doesn't save.

### ISSUE THREAD

**Issue by smallerYeet** [mxswat/pz-transmog-definitive-edition#5]
Hello, I'm playing on a dedicated Server with some mods and I have an issue.
The issue is that the Transmog gets lost when you unequip and equip your clothing.

Thus every time you change clothes, everything is reset.

**Comment by mxswat** [comment]
Fixed in Revision 5. Let me know if it's working for you:

https://steamcommunity.com/sharedfiles/filedetails/changelog/2979375840
